import type { MotionSpec } from './types';

/**
 * ACTIVE MOTION — functional interface movement.
 *
 * Every entry here answers the question "what is happening, and why should the
 * viewer care". If a motion cannot answer that, it belongs in `passive.ts`.
 *
 * House rule: one active motion carries a moment. A second active motion may
 * follow it in sequence (cursor travels → click → window opens), but two
 * unrelated active motions must never run at the same time.
 */
export const activeMotion: MotionSpec[] = [
  {
    id: 'cursor-move',
    label: 'Cursor movement',
    class: 'active',
    layer: 'cursor',
    intent: 'Directs attention. The pointer is the narrator of a desktop composition.',
    trigger: 'Start of a beat, or a hand-off from a previous action.',
    duration: 'motion.duration-sequence',
    easing: 'motion.ease-cursor',
    properties: ['transform: translate'],
    loop: false,
    notes: 'Travel along a slightly non-linear path. Arrive before the action, never simultaneously.',
  },
  {
    id: 'cursor-click',
    label: 'Click',
    class: 'active',
    layer: 'cursor',
    intent: 'Marks the exact instant of a decision.',
    trigger: 'Cursor arrival on a target.',
    duration: 'motion.duration-tap',
    easing: 'motion.ease-ui',
    properties: ['transform: scale', 'opacity'],
    loop: false,
    utilityClass: 'w98-motion-click',
    notes: 'Pair with the target control entering its pressed bevel on the same frame.',
  },
  {
    id: 'cursor-double-click',
    label: 'Double click',
    class: 'active',
    layer: 'cursor',
    intent: 'Opening something — the desktop metaphor for "enter".',
    trigger: 'Cursor arrival on a desktop icon or file.',
    duration: 'motion.duration-fast',
    easing: 'motion.ease-ui',
    properties: ['transform: scale', 'opacity'],
    loop: false,
    notes: 'Two taps separated by ~90ms, then a beat of stillness before the window opens.',
  },
  {
    id: 'cursor-drag',
    label: 'Drag',
    class: 'active',
    layer: 'cursor',
    intent: 'Shows a relationship being made: moving, sorting, connecting.',
    trigger: 'Press held on a draggable object.',
    duration: 'motion.duration-sequence',
    easing: 'motion.ease-cursor',
    properties: ['transform: translate'],
    loop: false,
    notes: 'The dragged object follows one frame behind the cursor. Classic 98 shows an outline, not the object.',
  },
  {
    id: 'window-open',
    label: 'Window open',
    class: 'active',
    layer: 'window',
    intent: 'Introduces new content as a new context.',
    trigger: 'Double click, menu command, or a new beat.',
    duration: 'motion.duration-window',
    easing: 'motion.ease-open',
    properties: ['transform: scale', 'opacity', 'clip-path'],
    loop: false,
    utilityClass: 'w98-motion-window-open',
    notes: 'Authentic 98 grows an outline rectangle from the origin. A short scale-from-origin reads the same at video speed.',
  },
  {
    id: 'window-close',
    label: 'Window close',
    class: 'active',
    layer: 'window',
    intent: 'Ends a context. Useful for clearing a slide before the payoff.',
    trigger: 'Close button, or the end of a beat.',
    duration: 'motion.duration-base',
    easing: 'motion.ease-close',
    properties: ['transform: scale', 'opacity'],
    loop: false,
    utilityClass: 'w98-motion-window-close',
  },
  {
    id: 'window-minimize',
    label: 'Minimize',
    class: 'active',
    layer: 'window',
    intent: 'Sets something aside without discarding it.',
    trigger: 'Minimize button.',
    duration: 'motion.duration-window',
    easing: 'motion.ease-close',
    properties: ['transform: scale', 'transform: translate', 'opacity'],
    loop: false,
    notes: 'Collapses toward the taskbar edge, not toward the centre.',
  },
  {
    id: 'window-maximize',
    label: 'Maximize',
    class: 'active',
    layer: 'window',
    intent: 'Escalation — this is now the whole subject.',
    trigger: 'Maximize button or double click on the title bar.',
    duration: 'motion.duration-window',
    easing: 'motion.ease-open',
    properties: ['width', 'height', 'transform: translate'],
    loop: false,
    notes: 'Strong first-slide move: a small window becomes the full frame.',
  },
  {
    id: 'button-press',
    label: 'Button press',
    class: 'active',
    layer: 'control',
    intent: 'Confirms an input was taken.',
    trigger: 'Click on a raised control.',
    duration: 'motion.duration-instant',
    easing: 'motion.step-1',
    properties: ['box-shadow', 'transform: translate'],
    loop: false,
    utilityClass: 'w98-motion-press',
    notes: 'Instant, not eased. The bevel flips to pressed and the label shifts 1px down-right.',
  },
  {
    id: 'checkbox-toggle',
    label: 'Checkbox toggle',
    class: 'active',
    layer: 'control',
    intent: 'A binary decision, made visible.',
    trigger: 'Click on a checkbox.',
    duration: 'motion.duration-instant',
    easing: 'motion.step-1',
    properties: ['opacity'],
    loop: false,
    notes: 'The check mark appears in one frame. Never fade, never spring.',
  },
  {
    id: 'radio-select',
    label: 'Radio select',
    class: 'active',
    layer: 'control',
    intent: 'A choice among alternatives — good for comparison beats.',
    trigger: 'Click on a radio option.',
    duration: 'motion.duration-instant',
    easing: 'motion.step-1',
    properties: ['opacity'],
    loop: false,
    notes: 'The previously selected dot clears on the same frame the new one lands.',
  },
  {
    id: 'dropdown-open',
    label: 'Dropdown open',
    class: 'active',
    layer: 'control',
    intent: 'Reveals a set of options — a list, a taxonomy, a set of answers.',
    trigger: 'Click on a combo box or menu title.',
    duration: 'motion.duration-fast',
    easing: 'motion.ease-ui',
    properties: ['clip-path', 'height'],
    loop: false,
    utilityClass: 'w98-motion-dropdown',
    notes: 'Unrolls downward with no fade. 98 menus are opaque and immediate.',
  },
  {
    id: 'menu-navigate',
    label: 'Menu navigation',
    class: 'active',
    layer: 'control',
    intent: 'Walks the viewer through a structure step by step.',
    trigger: 'Cursor moving down an open menu.',
    duration: 'motion.duration-fast',
    easing: 'motion.step-1',
    properties: ['background-color', 'color'],
    loop: false,
    notes: 'Highlight snaps item to item. Dwell ~400ms on the item that matters.',
  },
  {
    id: 'progress-fill',
    label: 'Progress bar',
    class: 'active',
    layer: 'control',
    intent: 'Shows a process advancing — time passing, work being done.',
    trigger: 'Start of a process beat.',
    duration: 'motion.duration-sequence',
    easing: 'motion.step-12',
    properties: ['width'],
    loop: false,
    utilityClass: 'w98-motion-progress',
    notes: 'Must advance in discrete chunks. A smooth fill breaks the illusion instantly.',
  },
  {
    id: 'loading',
    label: 'Loading / busy',
    class: 'active',
    layer: 'system',
    intent: 'Holds a beat: something is being computed.',
    trigger: 'A command that cannot resolve immediately.',
    duration: 'motion.duration-ambient',
    easing: 'motion.step-8',
    properties: ['content', 'transform: rotate'],
    loop: true,
    notes: 'Active despite looping — it reports state. Cap it at one per composition.',
  },
  {
    id: 'typing',
    label: 'Typing',
    class: 'active',
    layer: 'text',
    intent: 'Text arriving as thought, at reading pace.',
    trigger: 'Focus landing on a field, or the start of a text beat.',
    duration: 'motion.duration-sequence',
    easing: 'motion.step-24',
    properties: ['width', 'content'],
    loop: false,
    utilityClass: 'w98-motion-typing',
    notes: 'Character-stepped. Pair with a blinking caret; never with a moving cursor.',
  },
  {
    id: 'selection',
    label: 'Selection',
    class: 'active',
    layer: 'text',
    intent: 'Isolates the exact words that matter.',
    trigger: 'Drag across text, or a highlight beat.',
    duration: 'motion.duration-base',
    easing: 'motion.step-12',
    properties: ['background-color', 'color', 'width'],
    loop: false,
    utilityClass: 'w98-motion-select',
    notes: 'The classic navy fill sweeping left to right. The strongest emphasis tool in the system.',
  },
  {
    id: 'dialog-open',
    label: 'Dialog',
    class: 'active',
    layer: 'window',
    intent: 'Interrupts. Use for the turn in an argument.',
    trigger: 'A command, an error, or a decision point.',
    duration: 'motion.duration-fast',
    easing: 'motion.ease-open',
    properties: ['transform: scale', 'opacity'],
    loop: false,
    utilityClass: 'w98-motion-dialog',
    notes: 'Appears fast and centred. Everything else stops moving while it is on screen.',
  },
  {
    id: 'error-popup',
    label: 'Error dialog',
    class: 'active',
    layer: 'window',
    intent: 'The hard stop. The problem statement of a composition.',
    trigger: 'A failure beat.',
    duration: 'motion.duration-fast',
    easing: 'motion.ease-open',
    properties: ['transform: scale', 'transform: translate', 'opacity'],
    loop: false,
    notes: 'May stack two or three times for escalation — but that is the whole slide, nothing else moves.',
  },
  {
    id: 'scrollbar-drag',
    label: 'Scrollbar',
    class: 'active',
    layer: 'control',
    intent: 'Reveals that there is more than fits — depth, volume, scale.',
    trigger: 'Drag on the thumb, or an auto-scroll beat.',
    duration: 'motion.duration-sequence',
    easing: 'motion.ease-ui',
    properties: ['transform: translate'],
    loop: false,
    notes: 'The thumb and the content move together, at proportional distance.',
  },
];
