import type { MotionSpec } from './types';

/**
 * PASSIVE MOTION — atmosphere.
 *
 * Passive motion makes a still composition feel like a running machine. It
 * carries no meaning, so it must never be the loudest thing on screen and must
 * never sit on top of a headline.
 *
 * Budget: at most two passive loops visible at once, and never inside the same
 * optical area as an active motion.
 */
export const passiveMotion: MotionSpec[] = [
  {
    id: 'ascii-loop',
    label: 'ASCII animation',
    class: 'passive',
    layer: 'ascii',
    intent: 'Gives an ASCII illustration a pulse, so the frame reads as alive rather than printed.',
    trigger: 'Ambient; runs for the whole beat.',
    duration: 'motion.duration-ambient',
    easing: 'motion.step-8',
    properties: ['content'],
    loop: true,
    utilityClass: 'w98-motion-ascii-loop',
    notes: 'Frame-swap on a monospaced grid. Frame count should stay under 12 — this is text-mode, not video.',
  },
  {
    id: 'char-cycle',
    label: 'Character cycling',
    class: 'passive',
    layer: 'ascii',
    intent: 'Suggests computation or scanning without stating anything.',
    trigger: 'Ambient, or as a short reveal before text settles.',
    duration: 'motion.duration-fast',
    easing: 'motion.step-4',
    properties: ['content'],
    loop: true,
    utilityClass: 'w98-motion-char-cycle',
    notes: 'Cycle through a ramp from `src/ascii/charsets.ts`. Limit to a few glyphs, not a whole paragraph.',
  },
  {
    id: 'glyph-blink',
    label: 'Blinking glyph',
    class: 'passive',
    layer: 'ascii',
    intent: 'A single point of life — a cursor block, an asterisk, a marker.',
    trigger: 'Ambient.',
    duration: 'motion.blink-rate',
    easing: 'motion.step-1',
    properties: ['opacity'],
    loop: true,
    utilityClass: 'w98-motion-blink',
    notes: 'Hard on/off. Never fade a blink — a text-mode blink has two states.',
  },
  {
    id: 'pixel-flicker',
    label: 'Pixel flicker',
    class: 'passive',
    layer: 'ascii',
    intent: 'CRT texture. Reads as material, not as effect.',
    trigger: 'Ambient.',
    duration: 'motion.duration-ambient-slow',
    easing: 'motion.step-12',
    properties: ['opacity'],
    loop: true,
    utilityClass: 'w98-motion-flicker',
    notes: 'Amplitude must stay under ~8% opacity swing. If it is noticeable on first watch, it is too strong.',
  },
  {
    id: 'status-indicator',
    label: 'Status indicator',
    class: 'passive',
    layer: 'system',
    intent: 'Small proof that the system is running: a pulsing LED, a ticking counter.',
    trigger: 'Ambient, usually in a status bar.',
    duration: 'motion.duration-ambient',
    easing: 'motion.step-2',
    properties: ['opacity', 'background-color'],
    loop: true,
    utilityClass: 'w98-motion-indicator',
  },
  {
    id: 'caret-blink',
    label: 'Caret blink',
    class: 'passive',
    layer: 'text',
    intent: 'Marks a place where input could happen. Implies a person is present.',
    trigger: 'Ambient on a focused field or after typing stops.',
    duration: 'motion.blink-rate',
    easing: 'motion.step-1',
    properties: ['opacity'],
    loop: true,
    utilityClass: 'w98-motion-caret',
  },
  {
    id: 'dither-drift',
    label: 'Dither drift',
    class: 'passive',
    layer: 'ascii',
    intent: 'A slow-moving shading field behind or beside content.',
    trigger: 'Ambient background texture.',
    duration: 'motion.duration-ambient-drift',
    easing: 'motion.ease-linear',
    properties: ['background-position', 'opacity'],
    loop: true,
    utilityClass: 'w98-motion-drift',
    notes: 'Runs at ascii.opacity-ambient. Never crosses the headline block.',
  },
  {
    id: 'marquee-scroll',
    label: 'Marquee scroll',
    class: 'passive',
    layer: 'system',
    intent: 'A ticker of secondary information along an edge.',
    trigger: 'Ambient in a status bar or a narrow strip.',
    duration: 'motion.duration-ambient-drift',
    easing: 'motion.ease-linear',
    properties: ['transform: translate'],
    loop: true,
    utilityClass: 'w98-motion-marquee',
    notes: 'Edge only. A marquee through the middle of a composition is noise.',
  },
];
